#include<stdio.h>
#include<string.h>
#include<ctype.h>
main()
{
FILE *fp1,*fp2,*fp4,*fp3;
int op1[10],txtlen,txtlen1,i,j=0,len;
char add[5],locctr[5],mnemonic_value[5],start[10],temp[30],line[20],label[20],opcode[10],operand[10],symtab_label[10],code[10];
clrscr();
fp1=fopen("input.txt","r");
fp2=fopen("optab.txt","r");
fp3=fopen("symtab_label.txt","r");
fp4=fopen("length.txt","r");
fscanf(fp1,"%s%s%s%s",add,labelbel,opcode,operand);
if(strcmp(opcode,"START")==0)
{
strcpy(start,operand);
fscanf(fp4,"%d",&len);
}
printf("H^%s^%s^%d\nT^00%s^",label,start,len,start);
fscanf(fp1,"%s%s%s%s",add,labelbel,opcode,operand);

while(strcmp(opcode,"END")!=0)
{
fscanf(fp2,"%s%s",code,mnemonic_value);
while(!feof(fp2))
{
if(strcmp(opcode,code)==0)
{
fclose(fp2);
fscanf(fp3,"%s%s",locctr,symtab_label);
while(!feof(fp3))
{
if(strcmp(operand,symtab_label)==0)
{
printf("%s%s^",mnemonic_value,locctr);
break;
}
else
fscanf(fp3,"%s%s",locctr,symtab_label);
}
break;
}
else
fscanf(fp2,"%s%s",code,mnemonic_value);
}
if((strcmp(opcode,"BYTE")==0)||(strcmp(opcode,"WORD")==0))
{
if(strcmp(opcode,"WORD")==0)
printf("0000%s^",operand); //byte and word ne object code generate aavar illa
else
{
len=strlen(operand);
for(i=2;i<len;i++)
{
printf("%d",operand[i]);
}
printf("^");
}
}
fscanf(fp1,"%s%s%s%s",add,labelbel,opcode,operand);
fp2=fopen("optab.txt","r");
fseek(fp2,SEEK_SET,0);
}
printf("\nE^00%s",start);
fclose(fp1);
fclose(fp2);
fclose(fp3);
fclose(fp4);
fclose(fout);
getch();
}
